export * from './version.js';
export * from './template/element.js';
export * from './types/severity.js';
export * from './types/source-location.js';
export * from './types/violation.js';
export * from './types/audit-result.js';
export * from './rules/rule.interface.js';
export * from './rules/registry.js';
export { RULES_FR, type RuleLocale, type RuleWording } from './rules/locale-fr.js';
export type { RawCustomReport, RawCustomResult, RawCustomNode } from './rules/browser-entry.js';
export * from './scoring/score.js';
export * from './mapping/wcag.js';
export * from './mapping/rgaa.js';
export * from './mapping/coverage.js';
export * from './engine/collect.js';
export * from './engine/normalize.js';
