// Generated by scripts/build-rgaa-mapping.mjs — do not edit by hand.
//
// Source: https://raw.githubusercontent.com/DISIC/RGAA/master/v4.1/JSON/criteres.json
// SHA-256: ab231f4d763961bc16aa16228f2137f1d97c0769077bab11a4d392dfc13b0816
// RGAA 4.1.2 · 106 criteria across 13 topics
//
// Regenerate when the reference frame is updated, then review the diff: a change
// here changes what every audit cites.

import type { WcagLevel } from './wcag.js';

export interface RgaaCriterion {
  /** Dotted identifier, e.g. "1.1". */
  id: string;
  /** Topic number, 1 to 13. */
  topic: number;
  topicName: string;
  title: string;
  /** WCAG success criteria this RGAA criterion rests on. */
  wcag: readonly string[];
  /** Strictest level among those criteria; null when it references none. */
  level: WcagLevel | null;
  /** Number of tests the official method defines for this criterion. */
  testCount: number;
}

export const RGAA_SOURCE_CHECKSUM = 'ab231f4d763961bc16aa16228f2137f1d97c0769077bab11a4d392dfc13b0816';

export const RGAA_CRITERIA: readonly RgaaCriterion[] = [
  {
    "id": "1.1",
    "topic": 1,
    "topicName": "Images",
    "title": "Chaque image porteuse d'information a-t-elle une alternative textuelle ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 8
  },
  {
    "id": "1.2",
    "topic": 1,
    "topicName": "Images",
    "title": "Chaque image de décoration est-elle correctement ignorée par les technologies d'assistance ?",
    "wcag": [
      "1.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 6
  },
  {
    "id": "1.3",
    "topic": 1,
    "topicName": "Images",
    "title": "Pour chaque image porteuse d'information ayant une alternative textuelle, cette alternative est-elle pertinente (hors cas particuliers) ?",
    "wcag": [
      "1.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 9
  },
  {
    "id": "1.4",
    "topic": 1,
    "topicName": "Images",
    "title": "Pour chaque image utilisée comme CAPTCHA ou comme image-test, ayant une alternative textuelle, cette alternative permet-elle d'identifier la nature et la fonction de l'image ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 7
  },
  {
    "id": "1.5",
    "topic": 1,
    "topicName": "Images",
    "title": "Pour chaque image utilisée comme CAPTCHA, une solution d'accès alternatif au contenu ou à la fonction du CAPTCHA est-elle présente ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "1.6",
    "topic": 1,
    "topicName": "Images",
    "title": "Chaque image porteuse d'information a-t-elle, si nécessaire, une description détaillée ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 10
  },
  {
    "id": "1.7",
    "topic": 1,
    "topicName": "Images",
    "title": "Pour chaque image porteuse d'information ayant une description détaillée, cette description est-elle pertinente ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 6
  },
  {
    "id": "1.8",
    "topic": 1,
    "topicName": "Images",
    "title": "Chaque image texte porteuse d'information, en l'absence d'un mécanisme de remplacement, doit si possible être remplacée par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?",
    "wcag": [
      "1.4.5"
    ],
    "level": "AA",
    "testCount": 6
  },
  {
    "id": "1.9",
    "topic": 1,
    "topicName": "Images",
    "title": "Chaque légende d'image est-elle, si nécessaire, correctement reliée à l'image correspondante ?",
    "wcag": [
      "1.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 5
  },
  {
    "id": "2.1",
    "topic": 2,
    "topicName": "Cadres",
    "title": "Chaque cadre a-t-il un titre de cadre ?",
    "wcag": [
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "2.2",
    "topic": 2,
    "topicName": "Cadres",
    "title": "Pour chaque cadre ayant un titre de cadre, ce titre de cadre est-il pertinent ?",
    "wcag": [
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "3.1",
    "topic": 3,
    "topicName": "Couleurs",
    "title": "Dans chaque page web, l'information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?",
    "wcag": [
      "1.3.1",
      "1.4.1"
    ],
    "level": "A",
    "testCount": 6
  },
  {
    "id": "3.2",
    "topic": 3,
    "topicName": "Couleurs",
    "title": "Dans chaque page web, le contraste entre la couleur du texte et la couleur de son arrière-plan est-il suffisamment élevé (hors cas particuliers) ?",
    "wcag": [
      "1.4.3"
    ],
    "level": "AA",
    "testCount": 5
  },
  {
    "id": "3.3",
    "topic": 3,
    "topicName": "Couleurs",
    "title": "Dans chaque page web, les couleurs utilisées dans les composants d'interface ou les éléments graphiques porteurs d'informations sont-elles suffisamment contrastées (hors cas particuliers) ?",
    "wcag": [
      "1.4.11"
    ],
    "level": "AA",
    "testCount": 4
  },
  {
    "id": "4.1",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque média temporel pré-enregistré a-t-il, si nécessaire, une transcription textuelle ou une audiodescription (hors cas particuliers) ?",
    "wcag": [
      "1.2.1",
      "1.2.3"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "4.2",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Pour chaque média temporel pré-enregistré ayant une transcription textuelle ou une audiodescription synchronisée, celles-ci sont-elles pertinentes (hors cas particuliers) ?",
    "wcag": [
      "1.2.1",
      "1.2.3"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "4.3",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque média temporel synchronisé pré-enregistré a-t-il, si nécessaire, des sous-titres synchronisés (hors cas particuliers) ?",
    "wcag": [
      "1.2.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "4.4",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Pour chaque média temporel synchronisé pré-enregistré ayant des sous-titres synchronisés, ces sous-titres sont-ils pertinents ?",
    "wcag": [
      "1.2.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "4.5",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque média temporel pré-enregistré a-t-il, si nécessaire, une audiodescription synchronisée (hors cas particuliers) ?",
    "wcag": [
      "1.2.5"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "4.6",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Pour chaque média temporel pré-enregistré ayant une audiodescription synchronisée, celle-ci est-elle pertinente ?",
    "wcag": [
      "1.2.5"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "4.7",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque média temporel est-il clairement identifiable (hors cas particuliers) ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "4.8",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque média non temporel a-t-il, si nécessaire, une alternative (hors cas particuliers) ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "4.9",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Pour chaque média non temporel ayant une alternative, cette alternative est-elle pertinente ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "4.10",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque son déclenché automatiquement est-il contrôlable par l'utilisateur ?",
    "wcag": [
      "1.4.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "4.11",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "La consultation de chaque média temporel est-elle, si nécessaire, contrôlable par le clavier et tout dispositif de pointage ?",
    "wcag": [
      "2.1.1",
      "2.1.2"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "4.12",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "La consultation de chaque média non temporel est-elle contrôlable par le clavier et tout dispositif de pointage ?",
    "wcag": [
      "2.1.1",
      "2.1.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "4.13",
    "topic": 4,
    "topicName": "Multimédia",
    "title": "Chaque média temporel et non temporel est-il compatible avec les technologies d'assistance (hors cas particuliers) ?",
    "wcag": [
      "4.1.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "5.1",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Chaque tableau de données complexe a-t-il un résumé ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "5.2",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Pour chaque tableau de données complexe ayant un résumé, celui-ci est-il pertinent ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "5.3",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Pour chaque tableau de mise en forme, le contenu linéarisé reste-t-il compréhensible ?",
    "wcag": [
      "1.3.2",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "5.4",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Pour chaque tableau de données ayant un titre, le titre est-il correctement associé au tableau de données ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "5.5",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Pour chaque tableau de données ayant un titre, celui-ci est-il pertinent ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "5.6",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Pour chaque tableau de données, chaque en-tête de colonne et chaque en-tête de ligne sont-ils correctement déclarés ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 4
  },
  {
    "id": "5.7",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Pour chaque tableau de données, la technique appropriée permettant d'associer chaque cellule avec ses en-têtes est-elle utilisée (hors cas particuliers) ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 5
  },
  {
    "id": "5.8",
    "topic": 5,
    "topicName": "Tableaux",
    "title": "Chaque tableau de mise en forme ne doit pas utiliser d'éléments propres aux tableaux de données. Cette règle est-elle respectée ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "6.1",
    "topic": 6,
    "topicName": "Liens",
    "title": "Chaque lien est-il explicite (hors cas particuliers) ?",
    "wcag": [
      "1.1.1",
      "2.4.4",
      "2.5.3"
    ],
    "level": "A",
    "testCount": 5
  },
  {
    "id": "6.2",
    "topic": 6,
    "topicName": "Liens",
    "title": "Dans chaque page web, chaque lien a-t-il un intitulé ?",
    "wcag": [
      "1.1.1",
      "2.4.4"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "7.1",
    "topic": 7,
    "topicName": "Scripts",
    "title": "Chaque script est-il, si nécessaire, compatible avec les technologies d'assistance ?",
    "wcag": [
      "2.5.3",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "7.2",
    "topic": 7,
    "topicName": "Scripts",
    "title": "Pour chaque script ayant une alternative, cette alternative est-elle pertinente ?",
    "wcag": [
      "1.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "7.3",
    "topic": 7,
    "topicName": "Scripts",
    "title": "Chaque script est-il contrôlable par le clavier et par tout dispositif de pointage (hors cas particuliers) ?",
    "wcag": [
      "1.3.1",
      "2.1.1",
      "2.4.7"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "7.4",
    "topic": 7,
    "topicName": "Scripts",
    "title": "Pour chaque script qui initie un changement de contexte, l'utilisateur est-il averti ou en a-t-il le contrôle ?",
    "wcag": [
      "3.2.1",
      "3.2.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "7.5",
    "topic": 7,
    "topicName": "Scripts",
    "title": "Dans chaque page web, les messages de statut sont-ils correctement restitués par les technologies d'assistance ?",
    "wcag": [
      "4.1.3"
    ],
    "level": "AA",
    "testCount": 3
  },
  {
    "id": "8.1",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Chaque page web est-elle définie par un type de document ?",
    "wcag": [
      "4.1.1"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "8.2",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Pour chaque page web, le code source généré est-il valide selon le type de document spécifié ?",
    "wcag": [
      "4.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "8.3",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Dans chaque page web, la langue par défaut est-elle présente ?",
    "wcag": [
      "3.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "8.4",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Pour chaque page web ayant une langue par défaut, le code de langue est-il pertinent ?",
    "wcag": [
      "3.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "8.5",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Chaque page web a-t-elle un titre de page ?",
    "wcag": [
      "2.4.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "8.6",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Pour chaque page web ayant un titre de page, ce titre est-il pertinent ?",
    "wcag": [
      "2.4.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "8.7",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Dans chaque page web, chaque changement de langue est-il indiqué dans le code source (hors cas particuliers) ?",
    "wcag": [
      "3.1.2"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "8.8",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Dans chaque page web, le code de langue de chaque changement de langue est-il valide et pertinent ?",
    "wcag": [
      "3.1.2"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "8.9",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Dans chaque page web, les balises ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "8.10",
    "topic": 8,
    "topicName": "Éléments obligatoires",
    "title": "Dans chaque page web, les changements du sens de lecture sont-ils signalés ?",
    "wcag": [
      "1.3.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "9.1",
    "topic": 9,
    "topicName": "Structuration de l'information",
    "title": "Dans chaque page web, l'information est-elle structurée par l'utilisation appropriée de titres ?",
    "wcag": [
      "1.3.1",
      "2.4.1",
      "2.4.6",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "9.2",
    "topic": 9,
    "topicName": "Structuration de l'information",
    "title": "Dans chaque page web, la structure du document est-elle cohérente (hors cas particuliers) ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "9.3",
    "topic": 9,
    "topicName": "Structuration de l'information",
    "title": "Dans chaque page web, chaque liste est-elle correctement structurée ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "9.4",
    "topic": 9,
    "topicName": "Structuration de l'information",
    "title": "Dans chaque page web, chaque citation est-elle correctement indiquée ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "10.1",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans le site web, des feuilles de styles sont-elles utilisées pour contrôler la présentation de l'information ?",
    "wcag": [
      "1.3.1",
      "1.3.2"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "10.2",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, le contenu visible porteur d’information reste-t-il présent lorsque les feuilles de styles sont désactivées ?",
    "wcag": [
      "1.1.1",
      "1.3.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "10.3",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, l'information reste-t-elle compréhensible lorsque les feuilles de styles sont désactivées ?",
    "wcag": [
      "1.3.2",
      "2.4.3"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "10.4",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, le texte reste-t-il lisible lorsque la taille des caractères est augmentée jusqu'à 200%, au moins (hors cas particuliers) ?",
    "wcag": [
      "1.4.4"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "10.5",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, les déclarations CSS de couleurs de fond d'élément et de police sont-elles correctement utilisées ?",
    "wcag": [
      "1.4.3"
    ],
    "level": "AA",
    "testCount": 3
  },
  {
    "id": "10.6",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, chaque lien dont la nature n'est pas évidente est-il visible par rapport au texte environnant ?",
    "wcag": [
      "1.4.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "10.7",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, pour chaque élément recevant le focus, la prise de focus est-elle visible ?",
    "wcag": [
      "1.4.1",
      "2.4.7"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "10.8",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Pour chaque page web, les contenus cachés ont-ils vocation à être ignorés par les technologies d'assistance ?",
    "wcag": [
      "1.3.2",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "10.9",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, l'information ne doit pas être donnée uniquement par la forme, taille ou position. Cette règle est-elle respectée ?",
    "wcag": [
      "1.3.3",
      "1.4.1"
    ],
    "level": "A",
    "testCount": 4
  },
  {
    "id": "10.10",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, l'information ne doit pas être donnée par la forme, taille ou position uniquement. Cette règle est-elle implémentée de façon pertinente ?",
    "wcag": [
      "1.3.3",
      "1.4.1"
    ],
    "level": "A",
    "testCount": 4
  },
  {
    "id": "10.11",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?",
    "wcag": [
      "1.4.10"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "10.12",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, les propriétés d'espacement du texte peuvent-elles être redéfinies par l'utilisateur sans perte de contenu ou de fonctionnalité (hors cas particuliers) ?",
    "wcag": [
      "1.4.12"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "10.13",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, les contenus additionnels apparaissant à la prise de focus ou au survol d'un composant d'interface sont-ils contrôlables par l'utilisateur (hors cas particuliers) ?",
    "wcag": [
      "1.4.13"
    ],
    "level": "AA",
    "testCount": 3
  },
  {
    "id": "10.14",
    "topic": 10,
    "topicName": "Présentation de l'information",
    "title": "Dans chaque page web, les contenus additionnels apparaissant via les styles CSS uniquement peuvent-ils être rendus visibles au clavier et par tout dispositif de pointage ?",
    "wcag": [
      "2.1.1"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "11.1",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Chaque champ de formulaire a-t-il une étiquette ?",
    "wcag": [
      "1.3.1",
      "2.4.6",
      "3.3.2",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "11.2",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Chaque étiquette associée à un champ de formulaire est-elle pertinente (hors cas particuliers) ?",
    "wcag": [
      "2.4.6",
      "2.5.3",
      "3.3.2"
    ],
    "level": "A",
    "testCount": 6
  },
  {
    "id": "11.3",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, chaque étiquette associée à un champ de formulaire ayant la même fonction et répétée plusieurs fois dans une même page ou dans un ensemble de pages est-elle cohérente ?",
    "wcag": [
      "3.2.4"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "11.4",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, chaque étiquette de champ et son champ associé sont-ils accolés (hors cas particuliers) ?",
    "wcag": [
      "3.3.2"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "11.5",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, les champs de même nature sont-ils regroupés, si nécessaire ?",
    "wcag": [
      "1.3.1",
      "3.3.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "11.6",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, chaque regroupement de champs de même nature a-t-il une légende ?",
    "wcag": [
      "1.3.1",
      "3.3.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "11.7",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, chaque légende associée à un regroupement de champs de même nature est-elle pertinente ?",
    "wcag": [
      "1.3.1",
      "3.3.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "11.8",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, les items de même nature d'une liste de choix sont-ils regroupés de manière pertinente ?",
    "wcag": [
      "1.3.1"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "11.9",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, l'intitulé de chaque bouton est-il pertinent (hors cas particuliers) ?",
    "wcag": [
      "2.5.3",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "11.10",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, le contrôle de saisie est-il utilisé de manière pertinente (hors cas particuliers) ?",
    "wcag": [
      "3.3.1",
      "3.3.2"
    ],
    "level": "A",
    "testCount": 7
  },
  {
    "id": "11.11",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Dans chaque formulaire, le contrôle de saisie est-il accompagné, si nécessaire, de suggestions facilitant la correction des erreurs de saisie ?",
    "wcag": [
      "3.3.3"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "11.12",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "Pour chaque formulaire qui modifie ou supprime des données, ou qui transmet des réponses à un test ou à un examen, ou dont la validation a des conséquences financières ou juridiques, les données saisies peuvent-elles être modifiées, mises à jour ou récupérées par l'utilisateur ?",
    "wcag": [
      "3.3.4"
    ],
    "level": "AA",
    "testCount": 2
  },
  {
    "id": "11.13",
    "topic": 11,
    "topicName": "Formulaires",
    "title": "La finalité d'un champ de saisie peut-elle être déduite pour faciliter le remplissage automatique des champs avec les données de l'utilisateur ?",
    "wcag": [
      "1.3.5"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "12.1",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Chaque ensemble de pages dispose-t-il de deux systèmes de navigation différents, au moins (hors cas particuliers) ?",
    "wcag": [
      "2.4.5"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "12.2",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque ensemble de pages, le menu et les barres de navigation sont-ils toujours à la même place (hors cas particuliers) ?",
    "wcag": [
      "3.2.3"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "12.3",
    "topic": 12,
    "topicName": "Navigation",
    "title": "La page « plan du site » est-elle pertinente ?",
    "wcag": [
      "2.4.5"
    ],
    "level": "AA",
    "testCount": 3
  },
  {
    "id": "12.4",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque ensemble de pages, la page « plan du site » est-elle atteignable de manière identique ?",
    "wcag": [
      "2.4.5",
      "3.2.3"
    ],
    "level": "AA",
    "testCount": 3
  },
  {
    "id": "12.5",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque ensemble de pages, le moteur de recherche est-il atteignable de manière identique ?",
    "wcag": [
      "3.2.3"
    ],
    "level": "AA",
    "testCount": 3
  },
  {
    "id": "12.6",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Les zones de regroupement de contenus présentes dans plusieurs pages web (zones d'en-tête, de navigation principale, de contenu principal, de pied de page et de moteur de recherche) peuvent-elles être atteintes ou évitées ?",
    "wcag": [
      "1.3.1",
      "2.4.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "12.7",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque page web, un lien d'évitement ou d'accès rapide à la zone de contenu principal est-il présent (hors cas particuliers) ?",
    "wcag": [
      "2.4.1",
      "2.4.3",
      "3.2.3"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "12.8",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque page web, l'ordre de tabulation est-il cohérent ?",
    "wcag": [
      "2.4.3"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "12.9",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque page web, la navigation ne doit pas contenir de piège au clavier. Cette règle est-elle respectée ?",
    "wcag": [
      "2.1.1",
      "2.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "12.10",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque page web, les raccourcis clavier n'utilisant qu'une seule touche (lettre minuscule ou majuscule, ponctuation, chiffre ou symbole) sont-ils contrôlables par l’utilisateur ?",
    "wcag": [
      "2.1.4"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "12.11",
    "topic": 12,
    "topicName": "Navigation",
    "title": "Dans chaque page web, les contenus additionnels apparaissant au survol, à la prise de focus ou à l'activation d'un composant d'interface sont-ils si nécessaire atteignables au clavier ?",
    "wcag": [
      "2.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.1",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Pour chaque page web, l'utilisateur a-t-il le contrôle de chaque limite de temps modifiant le contenu (hors cas particuliers) ?",
    "wcag": [
      "2.2.1",
      "2.2.2"
    ],
    "level": "A",
    "testCount": 4
  },
  {
    "id": "13.2",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, l'ouverture d'une nouvelle fenêtre ne doit pas être déclenchée sans action de l'utilisateur. Cette règle est-elle respectée ?",
    "wcag": [
      "3.2.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.3",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, chaque document bureautique en téléchargement possède-t-il, si nécessaire, une version accessible (hors cas particuliers) ?",
    "wcag": [
      "1.1.1",
      "1.3.1",
      "1.3.2",
      "2.4.1",
      "2.4.3",
      "3.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.4",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Pour chaque document bureautique ayant une version accessible, cette version offre-t-elle la même information ?",
    "wcag": [
      "1.1.1",
      "1.3.1",
      "1.3.2",
      "2.4.1",
      "2.4.3",
      "3.1.1",
      "4.1.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.5",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, chaque contenu cryptique (art ASCII, émoticône, syntaxe cryptique) a-t-il une alternative ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.6",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, pour chaque contenu cryptique (art ASCII, émoticône, syntaxe cryptique) ayant une alternative, cette alternative est-elle pertinente ?",
    "wcag": [
      "1.1.1"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.7",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, les changements brusques de luminosité ou les effets de flash sont-ils correctement utilisés ?",
    "wcag": [
      "2.3.1"
    ],
    "level": "A",
    "testCount": 3
  },
  {
    "id": "13.8",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, chaque contenu en mouvement ou clignotant est-il contrôlable par l'utilisateur ?",
    "wcag": [
      "2.2.1",
      "2.2.2"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "13.9",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, le contenu proposé est-il consultable quelle que soit l'orientation de l'écran (portrait ou paysage) (hors cas particuliers) ?",
    "wcag": [
      "1.3.4"
    ],
    "level": "AA",
    "testCount": 1
  },
  {
    "id": "13.10",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, les fonctionnalités utilisables ou disponibles au moyen d'un geste complexe peuvent-elles être également disponibles au moyen d'un geste simple (hors cas particuliers) ?",
    "wcag": [
      "2.5.1"
    ],
    "level": "A",
    "testCount": 2
  },
  {
    "id": "13.11",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, les actions déclenchées au moyen d'un dispositif de pointage sur un point unique de l'écran peuvent-elles faire l'objet d'une annulation (hors cas particuliers) ?",
    "wcag": [
      "2.5.2"
    ],
    "level": "A",
    "testCount": 1
  },
  {
    "id": "13.12",
    "topic": 13,
    "topicName": "Consultation",
    "title": "Dans chaque page web, les fonctionnalités qui impliquent un mouvement de l'appareil ou vers l'appareil peuvent-elles être satisfaites de manière alternative (hors cas particuliers) ?",
    "wcag": [
      "2.5.4"
    ],
    "level": "A",
    "testCount": 3
  }
];
